version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.3
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
