AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ESImport Datadog Lambda function.

Parameters:
  RoleARN:
    Type: String

  EsUrl:
    Description: list of URLs that point to ElasticSearch cluster
    Type: String

  LookBackForXMinutes:
    Description: For how much minutes function will be looking back to find latest document
    Type: Number
    Default: 10

  SentryDsn:
    Description: DSN for Sentry service
    Type: String

  DatadogAPIKey:
    Description: API key for Datadog service
    Type: String

  DataDogEnv:
    Description: String that will be passed to  Datadog service as `host_name` param value
    Type: String

  LogLevel:
    Description: Log level for lambda function
    Type: String
    Default: INFO
    
Resources:
  LambdaEsimportDatadog:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: esimport_datadog.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ESImport Datadog Lambda function.
      MemorySize: 128
      Timeout: 3
      Role: !Ref RoleARN
      Environment:
        Variables:
          ES_URL: !Ref EsUrl
          SENTRY_DSN: !Ref SentryDsn
          DATADOG_API_KEY: !Ref DatadogAPIKey
          DATADOG_ENV: !Ref DataDogEnv
          LOOK_BACK_FOR_X_MINUTES: !Ref LookBackForXMinutes
          LOG_LEVEL: !Ref LogLevel

      Events:
        ScheduleLambda:
          Type: Schedule
          Properties:
            Schedule: cron(1/3 * * * ? *)
