AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sqs_consumer

  ESImport SQS to Elasticsearch worker

  '
Parameters:
  RoleARN:
    Type: String
  SNSTopicARN:
    Type: String
  EsUrl:
    Description: The URL to the target ElasticSearch cluster
    Type: String
  SentryDsn:
    Description: DSN for Sentry alerting
    Type: String
  ExecutionTimeout:
    Type: Number
    Default: 60
    Description: How long should the Lambda function run, consequently, the SQS VisibilityTimeout
      as well.
Resources:
  SQSConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout:
        Ref: ExecutionTimeout
      CodeUri: s3://lambda-artifacts-11/esimport/sqs_consumer/6ef457b90d2c720e1f286b3eb091511f
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Ref: RoleARN
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Ref: SNSTopicARN
          SQS_QUEUE_URL:
            Ref: MessagesQueue
          ES_URL:
            Ref: EsUrl
          SENTRY_DSN:
            Ref: SentryDsn
      Events:
        NewSQSMessage:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - MessagesQueue
              - Arn
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - MessagesDeadLetterQueue
          - Arn
  MessagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
        - '-'
        - - esimport-queue
          - Ref: AWS::Region
      VisibilityTimeout:
        Ref: ExecutionTimeout
  MessagesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
        - '-'
        - - esimport-dlq
          - Ref: AWS::Region
  MessagesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: MessagesQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:*
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: SNSTopicARN
  MessagesDeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: MessagesDeadLetterQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:*
          Resource:
            Fn::GetAtt:
            - MessagesQueue
            - Arn
  MessagesQueueToSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Fn::GetAtt:
        - MessagesQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn:
        Ref: SNSTopicARN
      Region: us-west-2
