AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sqs_consumer

  ESImport SQS to Elasticsearch worker

  '
Parameters:
  RoleARN:
    Type: String
  SNSTopicARN:
    Type: String
  ExecutionTimeout:
    Type: Number
    Default: 60
    Description: How long should the Lambda function run, consequently, the SQS VisibilityTimeout
      as well.
Resources:
  SQSConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout:
        Ref: ExecutionTimeout
      CodeUri: s3://distrodev-esimport-sqs-consumer/851e75e624ed705692f57d6ef4a5131c
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Ref: RoleARN
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Ref: SNSTopicARN
          SQS_QUEUE_URL:
            Ref: MessagesQueue
      Events:
        NewSQSMessage:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - MessagesQueue
              - Arn
  MessagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
        - '-'
        - - esimport-queue
          - Ref: AWS::Region
      VisibilityTimeout:
        Ref: ExecutionTimeout
  MessagesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: MessagesQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:*
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: SNSTopicARN
  MessagesQueueToSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Fn::GetAtt:
        - MessagesQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn:
        Ref: SNSTopicARN
