AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs_consumer

  ESImport SQS to Elasticsearch worker

Parameters:
  RoleARN:
    Type: String

  SNSTopicARN:
    Type: String

  DPSKSNSTopicARN:
    Type: String

  EsUrl:
    Description: The URL to the target ElasticSearch cluster
    Type: String

  SentryDsn:
    Description: DSN for Sentry alerting
    Type: String

  ExecutionTimeout:
    Type: Number
    Default: 60
    Description: How long should the Lambda function run, consequently, the SQS VisibilityTimeout as well.

  LogLevel:
    Description: Log level for lambda function
    Type: String
    Default: INFO

Conditions: 
  IsUSWestRegion: !Equals [ !Ref AWS::Region, us-west-2 ]

Resources:
  SQSConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: !Ref ExecutionTimeout
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !Ref RoleARN
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopicARN
          SQS_QUEUE_URL: !Ref MessagesQueue
          ES_URL: !Ref EsUrl
          SENTRY_DSN: !Ref SentryDsn

      Events:
        NewSQSMessage:
          Type: SQS
          Properties:
            Queue: !GetAtt MessagesQueue.Arn

      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt MessagesDeadLetterQueue.Arn # ARN of the SQS queue or SNS topic to use as DLQ. 


  # LambdaExecutionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: !Sub 'esimport-lambda-sqs-consumer-${AWS::Region}' 
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service:
  #           - lambda.amazonaws.com
  #         Action:
  #         - sts:AssumeRole
  #     Path: "/"
  #     Policies:
  #     - PolicyName: giveaccesstoqueueonly
  #       PolicyDocument:
  #         Version: '2012-10-17'
  #         Statement:
  #         - Effect: Allow
  #           Action:
  #           - sqs:*
  #           Resource:
  #           - !GetAtt MessagesQueue.Arn
  #     - PolicyName: root
  #       PolicyDocument:
  #         Version: '2012-10-17'
  #         Statement:
  #         - Effect: Allow
  #           Action:
  #           - logs:*
  #           Resource: arn:aws:logs:*:*:*


  # sns topics that SQS Consumer Lambda function depends on
  # ESRecordsSNS:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     DisplayName: "es-records-sns"


  MessagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        Fn::Join: 
        - "-"
        - - 'esimport-queue'
          - !Ref AWS::Region
      VisibilityTimeout: !Ref ExecutionTimeout


  MessagesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        Fn::Join: 
        - "-"
        - - 'esimport-dlq'
          - !Ref AWS::Region

  MessagesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MessagesQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: "*"
          Condition:
            ArnEquals:
              "aws:SourceArn": !Ref SNSTopicARN


  MessagesDeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MessagesDeadLetterQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: !GetAtt MessagesQueue.Arn

  MessagesQueueToSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt MessagesQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref SNSTopicARN
      Region: "us-west-2"


  # DPSK
  DPSKMessagesQueue:
    Type: AWS::SQS::Queue
    Condition: IsUSWestRegion
    Properties:
      QueueName: 
        Fn::Join: 
        - "-"
        - - 'esimport-dpsk-queue'
          - !Ref AWS::Region
      VisibilityTimeout: !Ref ExecutionTimeout


  DPSKMessagesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Condition: IsUSWestRegion
    Properties:
      QueueName: 
        Fn::Join: 
        - "-"
        - - 'esimport-dpsk-dlq'
          - !Ref AWS::Region

  DPSKMessagesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: IsUSWestRegion
    Properties:
      Queues:
        - !Ref DPSKMessagesQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: "*"
          Condition:
            ArnEquals:
              "aws:SourceArn": !Ref DPSKSNSTopicARN


  DPSKMessagesDeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: IsUSWestRegion
    Properties:
      Queues:
        - !Ref DPSKMessagesDeadLetterQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: !GetAtt DPSKMessagesQueue.Arn

  DPSKMessagesQueueToSnsSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsUSWestRegion
    Properties:
      Endpoint: !GetAtt DPSKMessagesQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref DPSKSNSTopicARN
      Region: "us-west-2"